baseURL = 'https://vlkozl.github.io'
copyright = "{year}" # To make 2007 - 2022. Just add before {year} example: 2007 - {year}
languageCode = 'en-US'
defaultContentLanguage = 'en'
theme = 'enchanted-lowkey'
title = 'Tools for Business Central'
enableRobotsTXT = true
summaryLength = 15
pagination.pagerSize = 5

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    # hl_Lines = ''
    # hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4
