[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "posts"
    name = "posts"
    url = "/posts"
    weight = 2   

[[main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 2

[[main]]
    identifier = "about"
    name = "About me"
    url = "/about"
    weight = 3

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 4
  
# Social Media Configuration

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/vlkozl"
    weight = 1