baseURL = 'https://vlkozl.github.io'
languageCode = 'en-us'
title = 'Tools for Business Central'

# Appearance settings
# theme = 'typo'
colorPalette = 'default'
hideHeader = false

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "Home"
homeIntroTitle = 'Welcome to bctools.dev!'
homeIntroContent = "I'm Vladimir Kozlov, a Software Engineer working with Microsoft Dynamics 365 Business Central."

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

# Intro on main page, content is markdown

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

[[params.social]]
name = "github"
url = "https://github.com/vlkozl"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/-vladimir-kozlov/"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'algol'

[module]
[[module.imports]]
path = "github.com/tomfran/typo"
